### PR TITLE
event filter tweak, no jpg directive, improved timestamp implementation, removal of rgbaToRGB

### PR DESCRIPTION
**Pull request by ppkantorski**
This modification should work a bit better with filtering event clicks.

### CODE REVIEW

**Comment by ppkantorski** [comment]
this is still a wip.  i'll see if i can improve it a bit more.

**Comment by ppkantorski** [comment]
Should be good now.  I did remove rgbaToRGB for non-experimental since it seemed to be unnecessary.  But I will have to update Ultrahand soon for the fixes to properly apply.

**Comment by J-D-K** [comment]
Thank you. I'll give it a look later today or tomorrow.

**Comment by ppkantorski** [comment]
I've also added the ability to remove jpg duplicates (compilation directive).  It is optional and used when building.

**Comment by J-D-K** [comment]
OK. Everything works fine and I understand a lot of the changes. I'm thinking of doing away with the memory hog version anyway after reading the code. The only thing I might do is make the JPEG deleting code easier for a user to turn on and off. Most people aren't going to be building PNGShot and building two versions for something that can be so easily turned on and off with a flag file or something doesn't seem efficient to me.

**Pull request merged**
